FIND_PROGRAM(LIBGCRYPTCONFIG_EXECUTABLE NAMES libgcrypt-config)

#reset variables
set(LIBGCRYPT_LIBRARIES)
set(LIBGCRYPT_CFLAGS)

# if libgcrypt-config has been found
IF(LIBGCRYPTCONFIG_EXECUTABLE)

    EXEC_PROGRAM(${LIBGCRYPTCONFIG_EXECUTABLE} ARGS --libs RETURN_VALUE _return_VALUE OUTPUT_VARIABLE LIBGCRYPT_LIBRARIES)

    EXEC_PROGRAM(${LIBGCRYPTCONFIG_EXECUTABLE} ARGS --cflags RETURN_VALUE _return_VALUE OUTPUT_VARIABLE LIBGCRYPT_CFLAGS)

    IF(${LIBGCRYPT_CFLAGS} MATCHES "\n")
        SET(LIBGCRYPT_CFLAGS " ")
    ENDIF(${LIBGCRYPT_CFLAGS} MATCHES "\n")

    IF(LIBGCRYPT_LIBRARIES AND LIBGCRYPT_CFLAGS)
        SET(LIBGCRYPT_FOUND TRUE)
    ENDIF(LIBGCRYPT_LIBRARIES AND LIBGCRYPT_CFLAGS)

ENDIF(LIBGCRYPTCONFIG_EXECUTABLE)

if (LIBGCRYPT_FOUND)
    if (NOT LibGcrypt_FIND_QUIETLY)
        message(STATUS "Found libgcrypt: ${LIBGCRYPT_LIBRARIES}")
    endif (NOT LibGcrypt_FIND_QUIETLY)
else (LIBGCRYPT_FOUND)
    if (LibGcrypt_FIND_REQUIRED)
        message(FATAL_ERROR "Could not find libgcrypt libraries")
    endif (LibGcrypt_FIND_REQUIRED)
endif (LIBGCRYPT_FOUND)

MARK_AS_ADVANCED(LIBGCRYPT_CFLAGS LIBGCRYPT_LIBRARIES)